pipeline{
    agent any
    environment{
        PROJECT_ID = 'flask-app-318214'
        LOCAL_TAG = 'app'
        REMOTE_TAG = 'eu.gcr.io/$PROJECT_ID/$LOCAL_TAG'
    }
    stages{
        stage('Build docker image'){
            steps{
                echo "===============Building docker image for ${LOCAL_TAG}==============="
                sh 'docker build -t $LOCAL_TAG -f app/Dockerfile app/'
            }
        }
        stage('Push docker image'){
            steps{
                echo 'TODO'
            }
        }
        stage('Run application'){
            steps{
                echo 'TODO'
            }
        }
    }
}